### ISSUE TITLE
Error in_array()

### ISSUE THREAD

**Issue by LordFit** [Taylor-pm-pl/WorldDefend#3]
`[Server thread/CRITICAL]: TypeError: "in_array(): Argument #2 ($haystack) must be of type array, bool given" (EXCEPTION) in "plugins/WorldDefend.phar/src/taylordevs/WorldDefend/event/CommandEvent" at line 46`

--- Stack trace ---
  #0 plugins/WorldDefend.phar/src/taylordevs/WorldDefend/event/CommandEvent(46): in_array(string[15] warpgui.command, false)
  #1 pmsrc/src/event/RegisteredListener(61): taylordevs\WorldDefend\event\CommandEvent->onCommand(object pocketmine\event\server\CommandEvent#197389)
  #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\CommandEvent#197389)

**Comment by taylordevs** [comment]
Fixed in 205c4423e2e6e99083a8d845d8735d4ac27df810
